#!/usr/bin/env bash
# this script configures nginx server so that
# /redirect_me is redirecting to another page

sudo apt update
sudo apt install -y nginx
echo 'Hello World!' | sudo tee /var/html/index.html
site="\\\trewrite ^/redirect_me https://masagaian.web.app/ permanent;\n"
sudo sed -i "40i $site" /etc/nginx/sites-available/default
service nginx start
