#!/usr/bin/env bash
# this script configures nginx server so that
# /redirect_me is redirecting to another page

sudo apt update
sudo apt install -y nginx
echo 'Hello World!' | sudo tee /var/html/index.html
site="\\\trewrite ^/redirect_me https://masagaian.web.app/ permanent;\n"
sudo sed -i "40i $site" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/my_404.html
code="\\\terror_page 404 /my_404.html;\n\tlocation = /my_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "40i $code" /etc/nginx/sites-enabled/default
service nginx restart
