#!/usr/bin/env bash
# this script configures the server to listen to port 80
sed -i 's/listen 8080/listen 80/' /etc/nginx/sites-enabled/default
sed -i 's/listen \[\:\:\]\:8080/listen \[\:\:\]\80' /etc/nginx/sites-enabled/default
service nginx restart
