#!/usr/bin/env bash
# this script configures the container to
# run nginx as user nginx and listening to
# active IPs on port 8080

pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo -i nginx service nginx start
